import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " dark:bg-dot-white/[0.2] bg-dot-black/[0.2]"
        }
      >
        <ClerkProvider>
          <div className="w-full p-6 pt-5 flex justify-center items-center fixed top-3 z-20">
            <Navbar />
          </div>
          <div className="pt-10">{children}</div>
        </ClerkProvider>
      </body>
    </html>
  );
}
